name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/${{ secrets.DIGITALOCEAN_REGISTRY_IMAGE }}:latest .

      - name: Push Docker image
        run: docker push registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/${{ secrets.DIGITALOCEAN_REGISTRY_IMAGE }}:latest
